#!/bin/sh
############################################################################

cvs2cl=/home/sigma/larsa/store/cvs/cvs2cl/cvs2cl.pl
dir=/home/sigma/larsa/code/coin/src/SoGUI

cd $dir

cvs update -dP

$cvs2cl --header stuff/ChangeLog.header --separate-header --prune \
  --ignore 'ChangeLog$' \
  --ignore '(Makefile\.in|configure|aclocal\.m4|config\.sub|config\.guess)$' \
  --ignore '(ltconfig|ltmain\.sh|missing|mkinstalldirs|stamp-h.*|install-sh)$' \
  --ignore 'config\.h\.in$' 

cvs commit -m "Automatic ChangeLog generation" ChangeLog

